version: '3.1'
services:
  db:
    image: postgres:12.11
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: zebrands
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: -p 5433

  python:
    image: python